### PR TITLE
Vendor gardener@v1.6.5; Implement migrate and restore

### PR DESCRIPTION
**Pull request by plkokanov**
**What this PR does / why we need it**:
Vendors gardener 1.6.5 and implements the Migrate and Restore functions to support control plane migration.

**Which issue(s) this PR fixes**:
Part of [#1631](https://github.com/gardener/gardener/issues/1631)

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Vendor gardener@v1.6.5
```
```improvement operator
Implement Migrate and Restore operations.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by rfranzke — CHANGES_REQUESTED** [review]
Can you also bump the versions in https://github.com/gardener/gardener-extension-os-coreos-alicloud/blob/master/Dockerfile

**Comment by plkokanov** [comment]
The new gardener version also makes it so that the os config extension controllers require list/get rbac rules for the cluster resource. I had modified it manually in my controller registrations some time ago and forgot to add it here.
Has to be added for gardener-extension-os-coreos as well.

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by ghost** [comment]
@plkokanov The pull request was assigned to you under `author-action`. Please unassign yourself when you are done. Thank you.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
